---
victorialogs_vars:
  kubernetes:
    namespace: monitoring
    node_selector:
      telemetry: "true"
    helm:
      chart:
        alias: vls
        name: victoria-logs-single
        version: v0.12.0
      repository:
        name: helm-charts
        org: VictoriaMetrics
        url: https://victoriametrics.github.io
    server:
      replicas: 1
      retention_period: 48h
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
      storage:
        enabled: true
        access_modes:
          - ReadWriteOnce
        class: longhorn
        size: 10Gi
    vector:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
