---
- name: Role Facts
  ansible.builtin.include_role:
    name: longhorn
    tasks_from: facts

- name: Role Reset
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Remove Helm release
      kubernetes.core.helm:
        name: '{{ longhorn_vars.kubernetes.helm.chart.name }}'
        namespace: '{{ longhorn_vars.kubernetes.namespace }}'
        state: absent
        kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
      ignore_errors: true

    - name: Remove Helm repository
      kubernetes.core.helm_repository:
        name: '{{ longhorn_vars.kubernetes.helm.repository.org }}'
        repo_state: absent
      ignore_errors: true

    - name: Remove storage directory
      ansible.builtin.file:
        path: '{{ longhorn_map.directory.data }}'
        state: absent
      ignore_errors: true
