---
- name: Role Facts
  ansible.builtin.include_role:
    name: longhorn
    tasks_from: facts

- name: Longhorn Validation
  when: (ansible_run_tags in [(), ('all',)]) or ('longhorn' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate release file url
      ansible.builtin.uri:
        url: '{{ longhorn_project.release.url }}/{{ longhorn_project.release.file }}'
        timeout: 5
      register: longhorn_result
      delay: 1
      retries: 3
      until: longhorn_result is not failed
      ignore_errors: true

    - name: Validate Helm repository
      kubernetes.core.helm_repository:
        name: '{{ longhorn_vars.kubernetes.helm.repository.org }}'
        repo_url: '{{ longhorn_vars.kubernetes.helm.repository.url }}'
        force_update: true
      ignore_errors: true

    - name: Validate kubeconfig exists
      ansible.builtin.stat:
        path: '{{ k3s_project.cluster.kubeconfig }}'
      register: longhorn_kubeconfig

    - name: Validate chart values can be templated
      ansible.builtin.debug:
        msg: "Chart values validation: OK"
        verbosity: 1
