---
- name: Role Facts
  ansible.builtin.include_role:
    name: victoria-metrics
    tasks_from: facts

- name: Role Reset
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Remove Helm releases
      kubernetes.core.helm:
        name: '{{ item }}'
        namespace: '{{ victoriametrics_vars.kubernetes.namespace }}'
        state: absent
        kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
      loop:
        - '{{ victoriametrics_vars.kubernetes.helm.chart.victoriametrics.alias }}'
        - '{{ victoriametrics_vars.kubernetes.helm.chart.prometheus.name }}'
      ignore_errors: true

    - name: Remove Helm repositories
      kubernetes.core.helm_repository:
        name: '{{ item.org }}'
        repo_state: absent
      loop:
        - "{{ victoriametrics_vars.kubernetes.helm.repository.prometheus }}"
        - "{{ victoriametrics_vars.kubernetes.helm.repository.victoriametrics }}"
      ignore_errors: true
