---
- name: create managed users
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | join(',') }}"
    shell: /bin/bash
    password: "!"
    update_password: on_create
    append: true
  loop: "{{ managed_users }}"
  tags:
    - user_management

- name: create ssh directories for managed users
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.ssh"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0700'
  loop: "{{ managed_users }}"
  tags:
    - user_management

- name: configure ssh public keys for managed users
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_public_key }}"
    state: present
  loop: "{{ managed_users }}"
  tags:
    - user_management

- name: ensure adm group has passwordless sudo access
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/adm-passwordless
    line: "%adm ALL=(ALL) NOPASSWD:ALL"
    create: true
    mode: '0440'
    validate: 'visudo -cf %s'
  tags:
    - user_management
