apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: home-pi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-operator-crds
      targetRevision: 28.0.1
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.74.1
      helm:
        releaseName: vmks
        valueFiles:
          - $values/apps/victoria-metrics/values.yaml
    - repoURL: git://192.168.1.57/home-pi-infrastructure
      targetRevision: master
      ref: values
