---
longhorn_vars:
  kubernetes:
    backup:
      enabled: false
    default_settings:
      collect_usage_metrics: false
      concurrent_automatic_engine_upgrade_limit: 1
      data_locality: best-effort
      log_level: Warn
      node_drain_policy: block-for-eviction
      pod_deletion_policy: delete-both-statefulset-and-deployment-pod
      recurring_successful_job_histories_limit: 0
      recurring_failed_job_histories_limit: 0
      volume:
        replica_auto_balance: least-effort
        replicas: 2
    frontend:
      gateway:
        service: longhorn-frontend
        subdomain: longhorn
      ingress:
        enabled: false
    helm:
      chart:
        name: longhorn
        version: v1.12.1
      repository:
        name: longhorn
        org: longhorn
        url: https://charts.longhorn.io
    namespace: longhorn
  release:
    file: longhornctl-linux-arm64
    repository:
      name: cli
      org: longhorn
    version: v1.12.1
