---
- name: Set map fact
  ansible.builtin.set_fact:
    argocd_map:
      helm:
        chart:
          reference: '{{ argocd_vars.kubernetes.helm.repository.name }}/{{ argocd_vars.kubernetes.helm.chart.name }}'
        timeout: 10m0s
      release:
        name: argocd
  run_once: true
