---
- name: reload promtail
  service:
    name: promtail
    enabled: yes
    daemon_reload: true
    state: restarted
- name: reload loki
  service:
    name: loki
    daemon_reload: true
    state: restarted
