---

- stat:
    path: "{{ install_path }}/{{ vault_version }}/"
  register: preexisting
  tags:
    - vault

- name: get vault version
  shell: "vault version | awk '{print $2}'"
  register: vault_version_shell_result
  when: preexisting.stat.exists == true
  tags:
    - vault

- set_fact: reported_vault_version="{{ vault_version_shell_result.stdout }}"
  when: preexisting.stat.exists == true
  tags:
    - vault

- block:

  - name: download vault
    get_url:
      url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_{{ arch }}.zip"
      dest: "{{ tmp_path }}"
      mode: 0777
      checksum: "{{ vault_checksum }}"
    tags:
      - vault

  - name: create the install paths
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - "{{ install_path }}/{{ vault_version }}"
      - /etc/vault
    tags:
      - vault

  - name: decompress archive
    unarchive:
      src: "{{ tmp_path }}"
      dest: "{{ install_path }}/{{ vault_version }}"
      remote_src: yes
    tags:
      - vault

  - name: link the versioned vault to the local bin
    file:
      src: "{{ install_path }}/{{ vault_version }}/vault"
      dest: "{{ bin_install_symlink_path }}"
      owner: root
      group: root
      state: link
    tags:
      - vault

  - name: remove the temp archives
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ tmp_path }}"
    tags:
      - vault

  when: (preexisting.stat.exists != true) or (reported_vault_version != vault_version_v_prefix)

- name: create group
  group:
    name: "{{ group }}"

- name: create user
  user:
    name: "{{ user }}"
    groups:
      - "{{ group }}"
    append: yes
    system: yes
    createhome: no

- name: configure vault
  template:
    src: vault.hcl.j2
    dest: "{{ config_path }}"
    mode: u=rw,g=r,o=r
  notify:
    - reload vault
  tags:
    - vault

- name: configure for systemd
  template:
    src: vault.service.j2
    dest: "{{ systemd_dir }}/vault.service"
    mode: 644
  notify:
    - reload vault
  tags:
    - vault
