---
- name: deploy k3s-maintenance script
  ansible.builtin.copy:
    src: k3s-maintenance
    dest: /usr/local/bin/k3s-maintenance
    mode: '0755'
    owner: root
    group: root
  tags:
    - k3s_maintenance
