---
- name: disable alsa-state.service
  ansible.builtin.systemd:
    name: alsa-state
    state: stopped
    enabled: false
  tags:
    - kill_audio

- name: disable alsa-restore.service
  ansible.builtin.systemd:
    name: alsa-restore
    state: stopped
    enabled: false
  tags:
    - kill_audio

- name: disable alsa-utils.service
  ansible.builtin.systemd:
    name: alsa-utils
    state: stopped
    enabled: false
  tags:
    - kill_audio

- name: disable onboard audio
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: '^dtparam=audio'
    line: 'dtparam=audio=off'
  notify: restart pi after config change
  tags:
    - kill_audio
