---

- name: include kill radios tasks
  include_tasks: kill_radios.yml

- name: include kill audio tasks
  include_tasks: kill_audio.yml

- name: include enable cgroups tasks
  include_tasks: enable_cgroups.yml

- name: include k3s hardware optimization tasks
  include_tasks: k3s_hardware_optimization.yml

- name: include kernel module blacklisting tasks
  include_tasks: blacklist_modules.yml

- name: include disable vim GUI tasks
  include_tasks: disable_vim_gui.yml

- name: include remove unnecessary services tasks
  include_tasks: remove_unnecessary_services.yml

- name: setting locale to {{ locale }}
  locale_gen:
    name: '{{ locale }}'
    state: present

- name: set timezone to {{ timezone }}
  timezone: name={{ timezone }}

- name: set keyboard layout to {{ keyboard_layout }}
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^XKBLAYOUT=.*$'
    line: 'XKBLAYOUT="{{ keyboard_layout }}"'
  register: keyboard_layout_result

- name: activate keyboard layout {{ keyboard_layout }}
  shell: "dpkg-reconfigure -f noninteractive keyboard-configuration"
  when: keyboard_layout_result.changed
  changed_when: false

- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist

- name: remove unattended-upgrades
  apt:
    name: unattended-upgrades
    state: absent

- name: install basic set of packages
  apt:
    pkg:
      - git
      - iotop
      - iftop
      - vim
      - dnsutils
      - jq
      - nmap
      - lsof
      - socat
      - tree
      - telnet
      - screen
      - siege
      - wrk
      - pwgen
    state: present

- name: include longhorn storage preparation tasks
  include_tasks: longhorn-storage.yml

