---

- name: setting locale to {{ locale }}
  locale_gen:
    name: '{{ locale }}'
    state: present

- name: set timezone to {{ timezone }}
  timezone: name={{ timezone }}

- name: set keyboard layout to {{ keyboard_layout }}
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^XKBLAYOUT=.*$'
    line: 'XKBLAYOUT="{{ keyboard_layout }}"'
  register: keyboard_layout_result

- name: add ios pubkey
  lineinfile:
    dest: /home/pi/.ssh/authorized_keys
    insertafter: EOF
    line: "{{ jdurbin_ios_ssh_pub_key }}"

- name: activate keyboard layout {{ keyboard_layout }}
  shell: "dpkg-reconfigure -f noninteractive keyboard-configuration"
  when: keyboard_layout_result.changed

- include: dns.yml
- include: packages.yml
