---
- name: repair stale apt source configuration
  ansible.builtin.include_tasks: repair_apt_sources.yml

- name: include config.txt (per-board boot config) tasks
  ansible.builtin.include_tasks: config_txt.yml

- name: include USB disk read-ahead tasks
  ansible.builtin.include_tasks: usb_read_ahead.yml

- name: include kill radios tasks
  ansible.builtin.include_tasks: kill_radios.yml

- name: include kill audio tasks
  ansible.builtin.include_tasks: kill_audio.yml

- name: include kernel module blacklisting tasks
  ansible.builtin.include_tasks: blacklist_modules.yml

- name: include disable vim GUI tasks
  ansible.builtin.include_tasks: disable_vim_gui.yml

- name: include remove unnecessary services tasks
  ansible.builtin.include_tasks: remove_unnecessary_services.yml

- name: setting locale to {{ locale }}
  community.general.locale_gen:
    name: '{{ locale }}'
    state: present

- name: set timezone to {{ timezone }}
  ansible.builtin.timezone:
    name: '{{ timezone }}'

- name: set keyboard layout to {{ keyboard_layout }}
  ansible.builtin.lineinfile:
    dest: /etc/default/keyboard
    regexp: '^XKBLAYOUT=.*$'
    line: 'XKBLAYOUT="{{ keyboard_layout }}"'
  register: keyboard_layout_result

- name: activate keyboard layout {{ keyboard_layout }}
  ansible.builtin.shell: dpkg-reconfigure -f noninteractive keyboard-configuration
  when: keyboard_layout_result.changed
  changed_when: false

- name: Update all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: include unattended-upgrades (automatic package updates) tasks
  ansible.builtin.include_tasks: unattended_upgrades.yml

- name: install basic set of packages
  ansible.builtin.apt:
    pkg:
      - git
      - iotop
      - iftop
      - vim
      - dnsutils
      - jq
      - nmap
      - lsof
      - socat
      - tree
      - telnet
      - screen
      - siege
      - wrk
      - pwgen
      - sysstat
      - fio
      - smartmontools
      - iperf3
      - wireguard-tools
    state: present
