---

- name: setting locale to {{ locale }}
  locale_gen:
    name: '{{ locale }}'
    state: present

- name: set timezone to {{ timezone }}
  timezone: name={{ timezone }}

- name: set keyboard layout to {{ keyboard_layout }}
  lineinfile:
    dest: /etc/default/keyboard
    regexp: '^XKBLAYOUT=.*$'
    line: 'XKBLAYOUT="{{ keyboard_layout }}"'
  register: keyboard_layout_result

- name: activate keyboard layout {{ keyboard_layout }}
  shell: "dpkg-reconfigure -f noninteractive keyboard-configuration"
  when: keyboard_layout_result.changed

- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist

- name: install basic set of packages
  apt:
    pkg:
      - git
      - iotop
      - iftop
      - vim
      - dnsutils
      - jq
      - nmap
      - redis-tools
      - prometheus-node-exporter
      - openjdk-17-jdk-headless
      - lsof
      - socat
      - tree
      - telnet
      - screen
      - golang-go
    state: present

- name: install unattended-upgrades
  apt:
    pkg:
      - unattended-upgrades
    state: present

- name: create apt auto-upgrades configuration
  template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: create unattended-upgrades configuration
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644

- name: register prometheus node exporter with consul
  community.general.consul:
    service_name: prometheus-node-exporter
    service_port: 9100
  tags:
    - prometheus