---
- name: remove mpris-proxy
  ansible.builtin.apt:
    name: mpris-proxy
    state: absent
  tags:
    - remove_services

- name: disable avahi-daemon
  ansible.builtin.systemd:
    name: avahi-daemon.service
    state: stopped
    enabled: false
  ignore_errors: true
  tags:
    - remove_services
